site_name: Icebreaker One Trust Framework Documentation
site_url: https://docs.icebreakerone.org
repo_url: https://github.com/icebreakerone/ib1-technical-docs
nav:
  - 'Guidelines':
    - 'Introduction to the IB1 Trust Framework': 'ops_guidelines/introduction.md'
    - 'Considerations before you start': 'ops_guidelines/before_starting.md'
    - 'Core Policies': 'ops_guidelines/common_policies.md'
    - 'Guidance for Data Consumers': 'ops_guidelines/data_consumer_ops_guidelines.md'
    - 'Guidance for Data Providers': 'ops_guidelines/data_provider_ops_guidelines.md'
    - 'Common Security Requirements': 'ops_guidelines/technical_common.md'
  - 'Trust Framework Architecture': 'architecture.md'
  - 'Data Providers':
    - 'Dataset Metadata': 'provider/metadata.md'
    - 'Access Control': 'provider/access_control.md'
  - 'Registry':
    - 'Registry Structure': 'registry/structure.md'
    - 'Scheme Catalog Requirements': 'registry/scheme_catalog_requirements.md'
  - 'Glossary': 'glossary.md'
  - 'Additional Material': 'additional_material.md'
  - 'Changelog': 'changelog.md'
theme:
  name: material
  features:
    - navigation.expand
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: overrides
  font:
    text: Open Sans
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: ib1-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: ib1-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - markdown_grid_tables
  - tables
  - attr_list
  - def_list
plugins:
  - social:
      cards_layout_options:
        background_color: "#0D1C22" 
        color: "#FFFFFF"
  - mike:
      alias_type: redirect
      redirect_template: "./mike/redirect.html"
