site_name: Icebreaker One Trust Framework Documentation
site_url: https://docs.icebreakerone.org
repo_url: https://github.com/icebreakerone/ib1-technical-docs
nav:
  - 'Introduction to the IB1 Trust framework': 'ops_guidelines/introduction.md'
  - 'Considerations before you start': 'ops_guidelines/before_starting.md'
  - 'Core Policies': 'ops_guidelines/common_policies.md'
  - 'Guidance for Data Consumers': 'ops_guidelines/data_consumer_ops_guidelines.md'
  - 'Guidance for Data Providers': 'ops_guidelines/data_provider_ops_guidelines.md'
  - 'Common Security Requirements': 'ops_guidelines/technical_common.md'
  - 'Trust Framework Architecture': 'architecture.md'
  - 'Dataset Metadata': 'metadata.md'
  - 'Access Control and Capability Grant Language': 'access_control_specification.md'
  - 'Glossary': 'glossary.md'
  - 'Additional Material': 'additional_material.md'
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: overrides
  font:
    text: Open Sans
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: ib1-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: ib1-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - markdown_grid_tables
  - tables
  - attr_list
plugins:
  - social:
      cards_color:
        fill: "#0D1C22" 
        text: "#FFFFFF"
  - mike:
      redirect_template: "mike/redirect.html"
